### ISSUE TITLE
feat: Allow for annotations on ingress instead using the Gatus kind

### ISSUE THREAD

**Issue by aumer-amr** [aumer-amr/gatus-operator#5]
Example yaml config:
```
enabled: true
client:
  dns-resolver: tcp://1.1.1.1:53
```

would be in annotations:
```
gatus.io/enabled: "true"
gatus.io/client.dns-resolver: "tcp://1.1.1.1:53"
```

However how to deal with maps, for example:
```
conditions:
      - "[STATUS] == 200"
      - "[BODY].status == UP"
      - "[RESPONSE_TIME] < 300"
```
This can either turn into a json array, or maybe another solution is better, feedback is required. Note: the name+value of an annotation can only be 256kb (which should be more than enough)

**Comment by mircea-pavel-anton** [comment]
Maybe something like this could work?

```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    gatus.io/enabled: "true"
    gatus.io/name: "test" # or deduced from the Ingress name
    gatus.io/group: "external" # or deduced from ingress class?
    gatus.io/client.dns-resolver: "tcp://1.1.1.1:53" #? could also have a default?
    gatus.io/interval: "1m" #? could be a default value
    gatus.io/conditions: |
      - "[STATUS] == 200"
      - "[BODY].status == UP"
      - "[RESPONSE_TIME] < 300"

spec:
  ingressClassName: nginx-example
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 80

```

Though I would use a different prefix and not `gatus.io/` since this is "Not affiliated with gatus.io". Maybe `aumer.gatus-operator/`?
